Controllers/EjerciciosFisicosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ProyectoCelular.Models;
using ProyectoCelular.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace ProyectoCelular.Controllers;

[Authorize]
public class EjerciciosFisicosController : Controller
{

    private ApplicationDbContext _context;

    //CONSTRUCTOR
    public EjerciciosFisicosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        // Crear una lista de SelectListItem que incluya el elemento adicional
        var selectListItems = new List<SelectListItem>
        {
            new SelectListItem { Value = "0", Text = "[SELECCIONE...]" }
        };

        // Obtener todas las opciones del enum
        var enumValues = Enum.GetValues(typeof(EstadoEmocional)).Cast<EstadoEmocional>();

        // Convertir las opciones del enum en SelectListItem
        selectListItems.AddRange(enumValues.Select(e => new SelectListItem
        {
            Value = e.GetHashCode().ToString(),
            Text = e.ToString().ToUpper()
        }));

        // Pasar la lista de opciones al modelo de la vista
        ViewBag.EstadoEmocionalInicio = selectListItems.OrderBy(t => t.Text).ToList();
        ViewBag.EstadoEmocionalFin = selectListItems.OrderBy(t => t.Text).ToList();

        var tipoEjercicios = _context.TipoEjercicios.ToList();
        tipoEjercicios.Add(new TipoEjercicio { TipoEjercicioId = 0, Descripcion = "[SELECCIONE...]" });
        ViewBag.TipoEjercicioId = new SelectList(tipoEjercicios.OrderBy(c => c.Descripcion), "TipoEjercicioId", "Descripcion");

        return View();
    }

    public JsonResult MostrarListadoEjercicios(int? id)
    {
        List<VistaEjercicios> MostrarEjercicios = new List<VistaEjercicios>();

        var ejerciciosFisicos = _context.EjerciciosFisicos.ToList();
        if (id != null)
        {
            ejerciciosFisicos = ejerciciosFisicos.Where(e => e.EjercicioFisicoID == id).ToList();
        }

        var Ejercicio = _context.TipoEjercicios.ToList();

        foreach (var ejercicioFisico in ejerciciosFisicos)
        {
            var ejercicio = Ejercicio.Where(e => e.TipoEjercicioId == ejercicioFisico.TipoEjercicioId).Single();

            var mostrarEjercicios = new VistaEjercicios
            {
                EjercicioFisicoID = ejercicioFisico.EjercicioFisicoID,
                TipoEjercicioID = ejercicioFisico.TipoEjercicioId,
                EjercicioNombre = ejercicio.Descripcion,
                InicioString = ejercicioFisico.Inicio.ToString("dd/MM/yyyy HH:mm"),
                FinString = ejercicioFisico.Fin.ToString("dd/MM/yyyy HH:mm"),
                EstadoEmocionalInicio = Enum.GetName(typeof(EstadoEmocional), ejercicioFisico.EstadoEmocionalInicio),
                EstadoEmocionalFin = Enum.GetName(typeof(EstadoEmocional), ejercicioFisico.EstadoEmocionalFin),
                Observaciones = ejercicioFisico.Observaciones
            };
            MostrarEjercicios.Add(mostrarEjercicios);
        }

        return Json(MostrarEjercicios);
    }

    public JsonResult GuardadoEjerciciosFisicos(int EjercicioFisicoID, int TipoEjercicioId, DateTime Inicio, DateTime Fin, EstadoEmocional EstadoEmocionalInicio, EstadoEmocional EstadoEmocionalFin, string? Observaciones)
    {

        string resultado = "";

        if (EjercicioFisicoID == 0)
        {
            var EjercicioFisico = new EjercicioFisico
            {
                EjercicioFisicoID = EjercicioFisicoID,
                TipoEjercicioId = TipoEjercicioId,
                Inicio = Inicio,
                Fin = Fin,
                EstadoEmocionalInicio = EstadoEmocionalInicio,
                EstadoEmocionalFin = EstadoEmocionalFin,
                Observaciones = Observaciones
            };
            _context.Add(EjercicioFisico);
            _context.SaveChanges();

            resultado = "Se guardo el ejercicio con exito";
        }
        else
        {
            var ejercicioFisicoEditar = _context.EjerciciosFisicos.Where(e => e.EjercicioFisicoID == EjercicioFisicoID).SingleOrDefault();

            {
                var existeEjercicioFisico = _context.EjerciciosFisicos.Where(e => e.EjercicioFisicoID == EjercicioFisicoID).Count();
                {
                    ejercicioFisicoEditar.EjercicioFisicoID = EjercicioFisicoID;
                    ejercicioFisicoEditar.TipoEjercicioId = TipoEjercicioId;
                    ejercicioFisicoEditar.Inicio = Inicio;
                    ejercicioFisicoEditar.Fin = Fin;
                    ejercicioFisicoEditar.EstadoEmocionalInicio = EstadoEmocionalInicio;
                    ejercicioFisicoEditar.EstadoEmocionalFin = EstadoEmocionalFin;
                    ejercicioFisicoEditar.Observaciones = Observaciones;
                    _context.SaveChanges();

                    resultado = "EJERCICIO INGRESADO";
                }
            }
        }

        return Json(resultado);


    }

    public JsonResult TraerListaEjercicios(int? EjercicioFisicoID)
    {
        var EjerciciosFisicos = _context.EjerciciosFisicos.ToList();

        if (EjercicioFisicoID != null)
        {
            EjerciciosFisicos = EjerciciosFisicos.Where(e => e.EjercicioFisicoID == EjercicioFisicoID).ToList();
        }

        return Json(EjerciciosFisicos.ToList());
    }

    public JsonResult EliminarEjerciciosFisicos(int EjercicioFisicoID)
    {
       var EjercicioFisico = _context.EjerciciosFisicos.Find(EjercicioFisicoID);
        _context.Remove(EjercicioFisico);
        _context.SaveChanges();

        return Json(true);
    }
}

Controllers/TipoEjerciciosController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoCelular.Data;
using ProyectoCelular.Models;
using Microsoft.AspNetCore.Authorization;


namespace ProyectoCelular.Controllers;

[Authorize]

public class TipoEjerciciosController : Controller
{
    private ApplicationDbContext _context;

    //CONSTRUCTOR
    public TipoEjerciciosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View();
    }

    public JsonResult ListadoTipoEjercicios(int? id)
    {
        //DEFINIMOS UNA VARIABLE EN DONDE GUARDAMOS EL LISTADO COMPLETO DE TIPOS DE EJERCICIOS
        var tipoDeEjercicios = _context.TipoEjercicios.ToList();


        //LUEGO PREGUNTAMOS SI EL USUARIO INGRESO UN ID
        //QUIERE DECIR QUE QUIERE UN EJERCICIO EN PARTICULAR
        if (id != null)
        {
            //FILTRAMOS EL LISTADO COMPLETO DE EJERCICIOS POR EL EJERCICIO QUE COINCIDA CON ESE ID
            tipoDeEjercicios = tipoDeEjercicios.Where(t => t.TipoEjercicioId == id).ToList();
        }

        return Json(tipoDeEjercicios);


    }

    public JsonResult GuardarTipoEjercicio(int tipoEjercicioID, string descripcion)
    {

        //1- VERIFICAMOS SI REALMENTE INGRESO ALGUN CARACTER Y LA VARIABLE NO SEA NULL
        // if (descripcion != null && descripcion != "")
        // {
        //     //INGRESA SI ESCRIBIO SI O SI
        // }

        // if (String.IsNullOrEmpty(descripcion) == false)
        // {
        //     //INGRESA SI ESCRIBIO SI O SI 
        // }

        string resultado = "";


        if (!String.IsNullOrEmpty(descripcion))
        {
            descripcion = descripcion.ToUpper();
            //INGRESA SI ESCRIBIO SI O SI 

            //2- VERIFICAR SI ESTA EDITANDO O CREANDO NUEVO REGISTRO

            if (tipoEjercicioID == 0)
            {
                //3- VERIFICAMOS SI EXISTE EN BASE DE DATOS UN REGISTRO CON LA MISMA DESCRIPCION
                //PARA REALIZAR ESA VERIFICACION BUSCAMOS EN EL CONTEXTO, ES DECIR EN BASE DE DATOS 
                //SI EXISTE UN REGISTRO CON ESA DESCRIPCION 

                var existeTipoEjercicio = _context.TipoEjercicios.Where(t => t.Descripcion == descripcion).Count();
                if (existeTipoEjercicio == 0)
                {
                    //4- GUARDAR EL TIPO DE EJERCICIO
                    var tipoEjercicio = new TipoEjercicio
                    {
                        Descripcion = descripcion.ToUpper()
                    };
                    _context.Add(tipoEjercicio);
                    _context.SaveChanges();
                    resultado = "Se guardo correctamente";
                }

                else
                {
                    resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                }


            }
            else
            {
                //QUIERE DECIR QUE VAMOS A EDITAR EL REGISTRO
                var tipoEjercicioEditar = _context.TipoEjercicios.Where(t => t.TipoEjercicioId == tipoEjercicioID).SingleOrDefault();
                if (tipoEjercicioEditar != null)

                {
                    //BUSCAMOS EN LA TABLA SI EXISTE UN REGISTRO CON EL MISMO NOMBRE PERO QUE EL ID SEA DISTINTO AL QUE ESTAMOS EDITANDO
                    var existeTipoEjercicio = _context.TipoEjercicios.Where(t => t.Descripcion == descripcion && t.TipoEjercicioId != tipoEjercicioID).Count();
                    if (existeTipoEjercicio == 0)
                    {
                        //QUIERE DECIR QUE EL ELEMENTO EXISTE Y ES CORRECTO ENTONCES CONTINUAMOS CON EL EDITAR
                        tipoEjercicioEditar.Descripcion = descripcion.ToUpper();
                        _context.SaveChanges();
                    }
                    else
                    {
                        resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                    }
                }

            }

        }

        else
        {
            resultado = "DEBE INGRESAR UNA DESCRIPCIÓN.";
        }
        return Json(resultado);


    }
     

    public JsonResult EliminarTipoEjercicio(int tipoEjercicioId)
    {
        var tipoEjercicio = _context.TipoEjercicios.Find(tipoEjercicioId);
        _context.Remove(tipoEjercicio);
        _context.SaveChanges();

        return Json(true);
    }



}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager



<!DOCTYPE html>
<html lang="sp">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ejercitar App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoCelular.styles.css" asp-append-version="true" />

</head>

<body>

@if(SignInManager.IsSignedIn (User))
{


<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoEjercicios" asp-action="Index">Tipo de ejercicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EjerciciosFisicos" asp-action="Index">Ejercicios Fisicos</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
</header>
 }

 else{<div class="container-fluid div-logout">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
 } 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>

</html>